export type MotionPresetName =
  | "fadeIn"
  | "fadeUp"
  | "fadeDown"
  | "fadeLeft"
  | "fadeRight"
  | "slideUp"
  | "slideDown"
  | "slideLeft"
  | "slideRight"
  | "cardStagger"
  | "softScale"
  | "scaleIn"
  | "fadeScale"
  | "successPulse"
  | "drawerSlide";
